### ISSUE TITLE
Layout units not staying in user selected pixel units

### ISSUE THREAD

**Issue by placegraphichere** [edge-reflow/issues#74]
Using some Layout values like padding and postion across more than one reflow size will often switch the values from pixels back to the default percentage units. Even when a user has changed it to pixels and "applied to all regions".

**Comment by jtlafferty** [comment]
Can you shared a project with us where this happens? It would be great to get a reproducible case. If you don't want to post it publicly, you can send it to tan at adobe.

**Comment by placegraphichere** [comment]
I reproduced it with some boxes, and did a screen capture. I've sent that to you. It seems to definitely happen within parented objects. I hadn't realized that may be key to the issue, but it may be important.

**Comment by jtlafferty** [comment]
Thanks, this bug was pretty easy to reproduce with the following steps.
1. Draw two boxes on the canvas (box2 inside box1)
2. Create a custom region and move to it.
3. In the region, change the left margin to use px and not percent for box2.
4. Create another region and move to it.
5. In the new region, nudge box2 to the right changing the margin left value.

Result: the margin left of box2 in the second region goes back to % while nudging the box.

**Comment by CoreyDotCom** [comment]
Fixed in latest code base.  Pending release.
